services:
  - type: worker
    name: Web-Screenshot-Bot
    env: python
    buildCommand: python -m pip install poetry : poetry install --no-dev && poetry shell
    startCommand: python __main__.py
    repo: https://github.com/sholoomail/Web-Screenshot-Bot.git
    branch: master
    envVars:
      - key: BOT_TOKEN 
        sync: false
      - key: API_ID 
        sync: false
      - key: API_HASH 
        sync: false
